// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: inventory.proto

package inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InventoryService_ReserveStock_FullMethodName           = "/inventory.InventoryService/ReserveStock"
	InventoryService_ReleaseStock_FullMethodName           = "/inventory.InventoryService/ReleaseStock"
	InventoryService_ConfirmStockDeduction_FullMethodName  = "/inventory.InventoryService/ConfirmStockDeduction"
	InventoryService_GetStockBySKU_FullMethodName          = "/inventory.InventoryService/GetStockBySKU"
	InventoryService_ListStocksByWarehouse_FullMethodName  = "/inventory.InventoryService/ListStocksByWarehouse"
	InventoryService_AddStockReceipt_FullMethodName        = "/inventory.InventoryService/AddStockReceipt"
	InventoryService_TransferStock_FullMethodName          = "/inventory.InventoryService/TransferStock"
	InventoryService_UpdateSafetyStockLevel_FullMethodName = "/inventory.InventoryService/UpdateSafetyStockLevel"
	InventoryService_GetLowStockItems_FullMethodName       = "/inventory.InventoryService/GetLowStockItems"
	InventoryService_CreateWarehouse_FullMethodName        = "/inventory.InventoryService/CreateWarehouse"
	InventoryService_UpdateWarehouseInfo_FullMethodName    = "/inventory.InventoryService/UpdateWarehouseInfo"
	InventoryService_ListWarehouses_FullMethodName         = "/inventory.InventoryService/ListWarehouses"
)

// InventoryServiceClient is the client API for InventoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventoryServiceClient interface {
	ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error)
	ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...grpc.CallOption) (*ReleaseStockResponse, error)
	ConfirmStockDeduction(ctx context.Context, in *ConfirmStockDeductionRequest, opts ...grpc.CallOption) (*ConfirmStockDeductionResponse, error)
	GetStockBySKU(ctx context.Context, in *GetStockBySKURequest, opts ...grpc.CallOption) (*GetStockBySKUResponse, error)
	ListStocksByWarehouse(ctx context.Context, in *ListStocksByWarehouseRequest, opts ...grpc.CallOption) (*ListStocksByWarehouseResponse, error)
	AddStockReceipt(ctx context.Context, in *AddStockReceiptRequest, opts ...grpc.CallOption) (*AddStockReceiptResponse, error)
	TransferStock(ctx context.Context, in *TransferStockRequest, opts ...grpc.CallOption) (*TransferStockResponse, error)
	UpdateSafetyStockLevel(ctx context.Context, in *UpdateSafetyStockLevelRequest, opts ...grpc.CallOption) (*UpdateSafetyStockLevelResponse, error)
	GetLowStockItems(ctx context.Context, in *GetLowStockItemsRequest, opts ...grpc.CallOption) (*GetLowStockItemsResponse, error)
	CreateWarehouse(ctx context.Context, in *CreateWarehouseRequest, opts ...grpc.CallOption) (*CreateWarehouseResponse, error)
	UpdateWarehouseInfo(ctx context.Context, in *UpdateWarehouseInfoRequest, opts ...grpc.CallOption) (*UpdateWarehouseInfoResponse, error)
	ListWarehouses(ctx context.Context, in *ListWarehousesRequest, opts ...grpc.CallOption) (*ListWarehousesResponse, error)
}

type inventoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInventoryServiceClient(cc grpc.ClientConnInterface) InventoryServiceClient {
	return &inventoryServiceClient{cc}
}

func (c *inventoryServiceClient) ReserveStock(ctx context.Context, in *ReserveStockRequest, opts ...grpc.CallOption) (*ReserveStockResponse, error) {
	out := new(ReserveStockResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReserveStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ReleaseStock(ctx context.Context, in *ReleaseStockRequest, opts ...grpc.CallOption) (*ReleaseStockResponse, error) {
	out := new(ReleaseStockResponse)
	err := c.cc.Invoke(ctx, InventoryService_ReleaseStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ConfirmStockDeduction(ctx context.Context, in *ConfirmStockDeductionRequest, opts ...grpc.CallOption) (*ConfirmStockDeductionResponse, error) {
	out := new(ConfirmStockDeductionResponse)
	err := c.cc.Invoke(ctx, InventoryService_ConfirmStockDeduction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetStockBySKU(ctx context.Context, in *GetStockBySKURequest, opts ...grpc.CallOption) (*GetStockBySKUResponse, error) {
	out := new(GetStockBySKUResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetStockBySKU_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListStocksByWarehouse(ctx context.Context, in *ListStocksByWarehouseRequest, opts ...grpc.CallOption) (*ListStocksByWarehouseResponse, error) {
	out := new(ListStocksByWarehouseResponse)
	err := c.cc.Invoke(ctx, InventoryService_ListStocksByWarehouse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) AddStockReceipt(ctx context.Context, in *AddStockReceiptRequest, opts ...grpc.CallOption) (*AddStockReceiptResponse, error) {
	out := new(AddStockReceiptResponse)
	err := c.cc.Invoke(ctx, InventoryService_AddStockReceipt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) TransferStock(ctx context.Context, in *TransferStockRequest, opts ...grpc.CallOption) (*TransferStockResponse, error) {
	out := new(TransferStockResponse)
	err := c.cc.Invoke(ctx, InventoryService_TransferStock_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) UpdateSafetyStockLevel(ctx context.Context, in *UpdateSafetyStockLevelRequest, opts ...grpc.CallOption) (*UpdateSafetyStockLevelResponse, error) {
	out := new(UpdateSafetyStockLevelResponse)
	err := c.cc.Invoke(ctx, InventoryService_UpdateSafetyStockLevel_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) GetLowStockItems(ctx context.Context, in *GetLowStockItemsRequest, opts ...grpc.CallOption) (*GetLowStockItemsResponse, error) {
	out := new(GetLowStockItemsResponse)
	err := c.cc.Invoke(ctx, InventoryService_GetLowStockItems_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) CreateWarehouse(ctx context.Context, in *CreateWarehouseRequest, opts ...grpc.CallOption) (*CreateWarehouseResponse, error) {
	out := new(CreateWarehouseResponse)
	err := c.cc.Invoke(ctx, InventoryService_CreateWarehouse_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) UpdateWarehouseInfo(ctx context.Context, in *UpdateWarehouseInfoRequest, opts ...grpc.CallOption) (*UpdateWarehouseInfoResponse, error) {
	out := new(UpdateWarehouseInfoResponse)
	err := c.cc.Invoke(ctx, InventoryService_UpdateWarehouseInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inventoryServiceClient) ListWarehouses(ctx context.Context, in *ListWarehousesRequest, opts ...grpc.CallOption) (*ListWarehousesResponse, error) {
	out := new(ListWarehousesResponse)
	err := c.cc.Invoke(ctx, InventoryService_ListWarehouses_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventoryServiceServer is the server API for InventoryService service.
// All implementations must embed UnimplementedInventoryServiceServer
// for forward compatibility
type InventoryServiceServer interface {
	ReserveStock(context.Context, *ReserveStockRequest) (*ReserveStockResponse, error)
	ReleaseStock(context.Context, *ReleaseStockRequest) (*ReleaseStockResponse, error)
	ConfirmStockDeduction(context.Context, *ConfirmStockDeductionRequest) (*ConfirmStockDeductionResponse, error)
	GetStockBySKU(context.Context, *GetStockBySKURequest) (*GetStockBySKUResponse, error)
	ListStocksByWarehouse(context.Context, *ListStocksByWarehouseRequest) (*ListStocksByWarehouseResponse, error)
	AddStockReceipt(context.Context, *AddStockReceiptRequest) (*AddStockReceiptResponse, error)
	TransferStock(context.Context, *TransferStockRequest) (*TransferStockResponse, error)
	UpdateSafetyStockLevel(context.Context, *UpdateSafetyStockLevelRequest) (*UpdateSafetyStockLevelResponse, error)
	GetLowStockItems(context.Context, *GetLowStockItemsRequest) (*GetLowStockItemsResponse, error)
	CreateWarehouse(context.Context, *CreateWarehouseRequest) (*CreateWarehouseResponse, error)
	UpdateWarehouseInfo(context.Context, *UpdateWarehouseInfoRequest) (*UpdateWarehouseInfoResponse, error)
	ListWarehouses(context.Context, *ListWarehousesRequest) (*ListWarehousesResponse, error)
	mustEmbedUnimplementedInventoryServiceServer()
}

// UnimplementedInventoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInventoryServiceServer struct {
}

func (UnimplementedInventoryServiceServer) ReserveStock(context.Context, *ReserveStockRequest) (*ReserveStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReserveStock not implemented")
}
func (UnimplementedInventoryServiceServer) ReleaseStock(context.Context, *ReleaseStockRequest) (*ReleaseStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseStock not implemented")
}
func (UnimplementedInventoryServiceServer) ConfirmStockDeduction(context.Context, *ConfirmStockDeductionRequest) (*ConfirmStockDeductionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmStockDeduction not implemented")
}
func (UnimplementedInventoryServiceServer) GetStockBySKU(context.Context, *GetStockBySKURequest) (*GetStockBySKUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStockBySKU not implemented")
}
func (UnimplementedInventoryServiceServer) ListStocksByWarehouse(context.Context, *ListStocksByWarehouseRequest) (*ListStocksByWarehouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListStocksByWarehouse not implemented")
}
func (UnimplementedInventoryServiceServer) AddStockReceipt(context.Context, *AddStockReceiptRequest) (*AddStockReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddStockReceipt not implemented")
}
func (UnimplementedInventoryServiceServer) TransferStock(context.Context, *TransferStockRequest) (*TransferStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferStock not implemented")
}
func (UnimplementedInventoryServiceServer) UpdateSafetyStockLevel(context.Context, *UpdateSafetyStockLevelRequest) (*UpdateSafetyStockLevelResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSafetyStockLevel not implemented")
}
func (UnimplementedInventoryServiceServer) GetLowStockItems(context.Context, *GetLowStockItemsRequest) (*GetLowStockItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLowStockItems not implemented")
}
func (UnimplementedInventoryServiceServer) CreateWarehouse(context.Context, *CreateWarehouseRequest) (*CreateWarehouseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWarehouse not implemented")
}
func (UnimplementedInventoryServiceServer) UpdateWarehouseInfo(context.Context, *UpdateWarehouseInfoRequest) (*UpdateWarehouseInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWarehouseInfo not implemented")
}
func (UnimplementedInventoryServiceServer) ListWarehouses(context.Context, *ListWarehousesRequest) (*ListWarehousesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWarehouses not implemented")
}
func (UnimplementedInventoryServiceServer) mustEmbedUnimplementedInventoryServiceServer() {}

// UnsafeInventoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventoryServiceServer will
// result in compilation errors.
type UnsafeInventoryServiceServer interface {
	mustEmbedUnimplementedInventoryServiceServer()
}

func RegisterInventoryServiceServer(s grpc.ServiceRegistrar, srv InventoryServiceServer) {
	s.RegisterService(&InventoryService_ServiceDesc, srv)
}

func _InventoryService_ReserveStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReserveStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReserveStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReserveStock(ctx, req.(*ReserveStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ReleaseStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ReleaseStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ReleaseStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ReleaseStock(ctx, req.(*ReleaseStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ConfirmStockDeduction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmStockDeductionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ConfirmStockDeduction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ConfirmStockDeduction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ConfirmStockDeduction(ctx, req.(*ConfirmStockDeductionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetStockBySKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStockBySKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetStockBySKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetStockBySKU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetStockBySKU(ctx, req.(*GetStockBySKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListStocksByWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStocksByWarehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListStocksByWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ListStocksByWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ListStocksByWarehouse(ctx, req.(*ListStocksByWarehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_AddStockReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddStockReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).AddStockReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_AddStockReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).AddStockReceipt(ctx, req.(*AddStockReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_TransferStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).TransferStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_TransferStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).TransferStock(ctx, req.(*TransferStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_UpdateSafetyStockLevel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSafetyStockLevelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).UpdateSafetyStockLevel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_UpdateSafetyStockLevel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).UpdateSafetyStockLevel(ctx, req.(*UpdateSafetyStockLevelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_GetLowStockItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLowStockItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).GetLowStockItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_GetLowStockItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).GetLowStockItems(ctx, req.(*GetLowStockItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_CreateWarehouse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWarehouseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).CreateWarehouse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_CreateWarehouse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).CreateWarehouse(ctx, req.(*CreateWarehouseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_UpdateWarehouseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWarehouseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).UpdateWarehouseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_UpdateWarehouseInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).UpdateWarehouseInfo(ctx, req.(*UpdateWarehouseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InventoryService_ListWarehouses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWarehousesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventoryServiceServer).ListWarehouses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventoryService_ListWarehouses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventoryServiceServer).ListWarehouses(ctx, req.(*ListWarehousesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventoryService_ServiceDesc is the grpc.ServiceDesc for InventoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.InventoryService",
	HandlerType: (*InventoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReserveStock",
			Handler:    _InventoryService_ReserveStock_Handler,
		},
		{
			MethodName: "ReleaseStock",
			Handler:    _InventoryService_ReleaseStock_Handler,
		},
		{
			MethodName: "ConfirmStockDeduction",
			Handler:    _InventoryService_ConfirmStockDeduction_Handler,
		},
		{
			MethodName: "GetStockBySKU",
			Handler:    _InventoryService_GetStockBySKU_Handler,
		},
		{
			MethodName: "ListStocksByWarehouse",
			Handler:    _InventoryService_ListStocksByWarehouse_Handler,
		},
		{
			MethodName: "AddStockReceipt",
			Handler:    _InventoryService_AddStockReceipt_Handler,
		},
		{
			MethodName: "TransferStock",
			Handler:    _InventoryService_TransferStock_Handler,
		},
		{
			MethodName: "UpdateSafetyStockLevel",
			Handler:    _InventoryService_UpdateSafetyStockLevel_Handler,
		},
		{
			MethodName: "GetLowStockItems",
			Handler:    _InventoryService_GetLowStockItems_Handler,
		},
		{
			MethodName: "CreateWarehouse",
			Handler:    _InventoryService_CreateWarehouse_Handler,
		},
		{
			MethodName: "UpdateWarehouseInfo",
			Handler:    _InventoryService_UpdateWarehouseInfo_Handler,
		},
		{
			MethodName: "ListWarehouses",
			Handler:    _InventoryService_ListWarehouses_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "inventory.proto",
}
